Speeding the model execution	
    Selecting Best Models When Preprocessing 
	Speeding Up Model Selection with Parallelization
	Speeding Up Model Selection Using Algorithm-Specific Methods
	Evaluating Performance After Model Selection

Selecting Best Models When Preprocessing
1. Rescale Data  -> MinMaxScaler (Sklearn)
2. Binarize Data (Make Binary)  
3. Standardize Data  

In [3]:
#Rescaling (between 0 to 1)
import pandas
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler
url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names = names)
array = dataframe.values
print(dataframe)
X = array[:,0:8]
Y = array[:,8]
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
numpy.set_printoptions(precision=3)  
print(rescaledX[0:5,:])

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]
[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


In [5]:
#Binarize data ->  Binarizer(Sklearn)

import pandas
import scipy
import numpy
from sklearn.preprocessing import Binarizer
url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names = names)
array = dataframe.values
print(dataframe)
X = array[:,0:8]
Y = array[:,8]
binarizer = Binarizer(threshold = 0.0).fit(X)
binaryX = binarizer.transform(X)
numpy.set_printoptions(precision = 3)
print(binaryX[0:5,:])

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]
[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
#3. Standardize Data  ->StandardScaler(sklearn)
import pandas
import scipy
import numpy
from sklearn.preprocessing import StandardScaler
url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names = names)
array = dataframe.values
print(dataframe)
X = array[:,0:8]
Y = array[:,8]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
numpy.set_printoptions(precision = 3)
print(rescaledX[0:5,:])

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]
[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0

#Speeding Up Model Selection with Parallelization

100 -> split to 10 parts and run parallely -> combine to create a single model


1.Using Pandas directly with two threads
2.Using Dask with threads and separate processes
3.Using Modin with a Ray/ Dask backend
4.Using multiprocessing.Pool to launch separate processes 
5.Using joblib.parallel to launch separate threads and processes 

pip install pandas==1.1.4
pip install dask==2.16.0
pip install modin[ray]==0.8.2

In [ ]:
#pip install pandas

In [ ]:
pip install dask

In [8]:
#Dask -> Paralell computing concept , Oracle ADS Lib

os.environ['MODIN_ENGINE'] = "ray"
import ray 
ray.init(num_gpus=0)
import modin.pandas as mpd
modin_df = mpd.DataFrame(pandas_df)

%%time 

modin_df['col2'] = modin_df['col2'] + 100.0 + random()
print(modin_df.head())

In [ ]:
Refer :https://github.com/VedaVinothiniShastra/DS_PT_1/blob/main/Spec-DS/Speeding_Up_Model_Selection_with_Parallelization.ipynb 

Speeding Up Model Selection Using Algorithm-Specific Methods

1.Probabilistic Measures -> Choose a model via in-sample error and complexity

    a.Akaike Information Criterion (AIC)->method for scoring and selecting a model
        AIC = -2/N * LL + 2 * k/N
        LL-> is the log-likelihood of the model
        N ->is the number of examples in the training dataset
        k ->is the number of parameters in the model
    
    b.Bayesian Information Criterion (BIC)->the model with the lowest BIC is selected
        BIC = -2 * LL + log(N) * k
        LL-> is the log-likelihood of the model
        N ->is the number of examples in the training dataset
        k ->is the number of parameters in the model
    
    c.Minimum Description Length (MDL)->the model with the lowest MDL is selected
        MDL = L(h) + L(D | h)
        h -> is the model
        D -> is the predictions made by the model
        L(h)-> is the number of bits required to represent the model
        L(D | h)-> is the number of bits required to represent the predictions from the model on the training dataset.
        
        
    d.Structural Risk Minimization (SRM)->balancing the model's complexity against its success at fitting the training data
    
2.Resampling Methods ->Choose a model via estimated out-of-sample error
    a.Random train/test splits.
    b.Cross-Validation (k-fold, LOOCV, etc.).
    c.Bootstrap

In [3]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
X, y = make_regression(n_samples=100, n_features=2, noise=0.1)
model = LinearRegression()
model.fit(X, y)
num_params = len(model.coef_) + 1
print('Number of parameters: %d' % (num_params))
yhat = model.predict(X)
mse = mean_squared_error(y, yhat)
print(mse)

Number of parameters: 3
0.010108623559815571


In [8]:
def calculate_aic(n, mse, num_params):
 aic = n * log(mse) + 2 * num_params
 return aic
def calculate_bic(n, mse, num_params):
 bic = n * log(mse) + num_params * log(n)
 return bic

In [9]:
from math import log
aic = calculate_aic(len(y), mse, num_params)
print('AIC',aic)
bic = calculate_bic(len(y), mse, num_params)
print('BIC',bic)

AIC -453.4366401626476
BIC -445.62112960468335


In [10]:
#LOOCV
from sklearn.datasets import make_blobs
from sklearn.model_selection import LeaveOneOut
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X, y = make_blobs(n_samples=100, random_state=1)
cv = LeaveOneOut()
y_true, y_pred = list(), list()
for train_ix, test_ix in cv.split(X):
    X_train, X_test = X[train_ix, :], X[test_ix, :]
    y_train, y_test = y[train_ix], y[test_ix]
    model = RandomForestClassifier(random_state=1)
    model.fit(X_train, y_train)
    yhat = model.predict(X_test)
    y_true.append(y_test[0])
    y_pred.append(yhat[0])
acc = accuracy_score(y_true, y_pred)
print(acc)

0.99


Evaluating Performance After Model Selection
refer : https://github.com/VedaVinothiniShastra/DS_PT_1/blob/main/Spec-DS/Day%2024.ipynb
        
Classification:
    1.Precision
    2.Recall
    3.F1 Score
    4.Confusion Matrix 
    5.ROC Curve Log loss
Regression:
    1.MSE
    2.MAE
    3.RMSE
    4.RMSLE
    5.R Squared
    6.Adjuested R Squared
Clustering :
    1.Adjusted Rand Index
    2.Rand Index
    3.Silhouette Score aka Silhouette Coefficient
    4.Davies-Bouldin Index ratio 
    5.Mutual Information
    

Neural Networks	
    Introduction
	Preprocessing Data for Neural Networks
	Designing a Neural Network
	Training a Binary Classifier
Neural Networks Multiclass Classifier	
    Training a Multiclass Classifier
	Training a Regressor
	Making Predictions
Addressing Overfitting Problem	
    Visualize Training History
	Reducing Overfitting with Weight Regularization
	Reducing Overfitting with Early Stopping
	Reducing Overfitting with Dropout
    

Neural Networks	->Inspired by biological neural networks
    Introduction
    Supervised, Unsupervised 
    Types of NN:
        1.multilayer perceptron ->uses a nonlinear activation function.
        2.convolutional neural network CNN ->used multilayer perceptrons.
        3.recursive neural network RNN ->uses weights to make structured predictions
        4.recurrent neural network  RNN ->use recurrent neural network architecture and does not use an activation function
        4.sequence-to-sequence modules (2 Recuurent NN & Shallow Nn)->use two recurrent networks and shallow neural networks which produce a vector space from an amount of text
        
	Preprocessing Data for Neural Networks 
    1.Min-Max Scaling
    2.Decimal Scaling
    3.Eliminating Outliers
    4.Z-score normalization or Standardization
    5.Mean / Median Absolute Deviation
    6.(Modified) Tanh Estimator
    7.Max-Scaling
    
	Designing a Neural Network
	Training a Binary Classifier

In [ ]:
Refer : https://github.com/VedaVinothiniShastra/DS_PT_1/blob/main/Spec-DS/Day%2031%20%26%2032.ipynb 
        
        from Preprocessing Data for Neural Networks to Reducing Overfitting with Dropout
        
    