Speeding the model execution	
    Selecting Best Models When Preprocessing
	Speeding Up Model Selection with Parallelization
	Speeding Up Model Selection Using Algorithm-Specific Methods
	Evaluating Performance After Model Selection
Neural Networks	
    Introduction
	Preprocessing Data for Neural Networks
	Designing a Neural Network
	Training a Binary Classifier

Selecting Best Models When Preprocessing
1. Rescale Data  -> MinMaxScaler (Sklearn)
2. Binarize Data (Make Binary)  
3. Standardize Data  

In [3]:
#Rescaling (between 0 to 1)
import pandas
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler
url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names = names)
array = dataframe.values
print(dataframe)
X = array[:,0:8]
Y = array[:,8]
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)
numpy.set_printoptions(precision=3)  
print(rescaledX[0:5,:])

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]
[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


In [5]:
#Binarize data ->  Binarizer(Sklearn)

import pandas
import scipy
import numpy
from sklearn.preprocessing import Binarizer
url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names = names)
array = dataframe.values
print(dataframe)
X = array[:,0:8]
Y = array[:,8]
binarizer = Binarizer(threshold = 0.0).fit(X)
binaryX = binarizer.transform(X)
numpy.set_printoptions(precision = 3)
print(binaryX[0:5,:])

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]
[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
#3. Standardize Data  ->StandardScaler(sklearn)
import pandas
import scipy
import numpy
from sklearn.preprocessing import StandardScaler
url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names = names)
array = dataframe.values
print(dataframe)
X = array[:,0:8]
Y = array[:,8]
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)
numpy.set_printoptions(precision = 3)
print(rescaledX[0:5,:])

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]
[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0

#Speeding Up Model Selection with Parallelization

100 -> split to 10 parts and run parallely -> combine to create a single model


1.Using Pandas directly with two threads
2.Using Dask with threads and separate processes
3.Using Modin with a Ray backend
4.Using multiprocessing.Pool to launch separate processes 
5.Using joblib.parallel to launch separate threads and processes 

pip install pandas==1.1.4
pip install dask==2.16.0
pip install modin[ray]==0.8.2

In [ ]:
#pip install pandas

In [ ]:
pip install dask

In [8]:
#Dask -> Paralell computing concept , Oracle ADS Lib

os.environ['MODIN_ENGINE'] = "ray"
import ray 
ray.init(num_gpus=0)
import modin.pandas as mpd
modin_df = mpd.DataFrame(pandas_df)

%%time 

modin_df['col2'] = modin_df['col2'] + 100.0 + random()
print(modin_df.head())

In [ ]:
Refer :https://github.com/VedaVinothiniShastra/DS_PT_1/blob/main/Spec-DS/Speeding_Up_Model_Selection_with_Parallelization.ipynb 